[package]
name = "sniffnet"
version = "1.0.1"
authors = ["Giuliano Bellini"]
edition = "2021"
description = "Application to comfortably monitor your network traffic"
readme = "README.md"
repository = "https://github.com/GyulyVGC/sniffnet"
license = "MIT OR Apache-2.0"
keywords = ["filter", "network", "packet", "sniffer", "parser"]
categories = ["command-line-utilities", "concurrency", "network-programming"]


[package.metadata.bundle]
name = "Sniffnet"
identifier = "gyulyvgc.sniffnet"
icon = ["./resources/icon.ico"]


[profile.release]
opt-level = 3
lto = true


[dependencies]
pcap = "0.11.0"
etherparse = "0.12.0"
chrono = "0.4.22"
thousands = "0.2.0"
plotters = "0.3.4"
indexmap = "1.9.1"
plotters-iced = "0.5.0"
iced = { version = "0.4.2", features = ["tokio"] }
iced_style = "0.4.0"