[package]
name = "sniffnet"
version = "1.1.4"
authors = ["Giuliano Bellini"]
edition = "2021"
description = "Application to comfortably monitor your network traffic"
readme = "README.md"
repository = "https://github.com/GyulyVGC/sniffnet"
license = "MIT OR Apache-2.0"
keywords = ["filter", "network", "packet", "sniffer", "gui"]
categories = ["visualization", "gui", "network-programming"]
include = ["src/**/*", "LICENSE-*", "README.md", "CHANGELOG.md", "resources/countries_flags/**/*", "resources/DB/GeoLite2-Country.mmdb", "resources/palettes/*", "resources/fonts/subset/*", "resources/sounds/*"]


[package.metadata.bundle]
name = "Sniffnet"
identifier = "gyulyvgc.sniffnet"
icon = ["./resources/logos/icon.ico"]


[profile.release]
opt-level = 3
lto = true
strip = true


[dependencies]
pcap = "1.0.0"
etherparse = "0.13.0"
chrono = { version = "0.4.24", default_features = false, features = ["clock"] }
thousands = "0.2.0"
indexmap = "1.9.3"
plotters = { version = "0.3.4", default_features = false, features = ["area_series"] }
iced = { version = "0.9.0", features = ["tokio", "image"] }
iced_native = "0.10.3"
iced_lazy = "0.6.1"
plotters-iced = "0.8.0"
maxminddb = "0.23.0"
confy = "0.5.1"
serde = { version = "1.0.163", default_features = false, features = ["derive"] }
rodio = { version = "0.17.1", default_features = false, features = ["mp3"] }
reqwest = { version = "0.11.17", features = ["json", "blocking"] }

[dev-dependencies]
rstest = "0.17.0"
